### ISSUE TITLE
Running "setup.py" does not find default or manual prefixes, causing installation failure.

### ISSUE THREAD

**Issue by 329gkp** [icecube/nuflux#16]
In building nuflux for GolemFit use, attempting to run setup.py for nuflux does not work on cvmfs for the default or manually-specified prefixes.  So far, I still do not have a fix.  Error output is below:

`    ERROR: Command errored out with exit status 1:
     command: /cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/RHEL_7_x86_64/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rwp99j4_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rwp99j4_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kpfell_t/install-record.txt --single-version-externally-managed --compile --user --prefix= --home=/tmp/pip-target-8zleredw
         cwd: /tmp/pip-req-build-rwp99j4_/
    Complete output (2 lines):
    running install
    error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
    ----------------------------------------
ERROR: Command errored out with exit status 1: /cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/RHEL_7_x86_64/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rwp99j4_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rwp99j4_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kpfell_t/install-record.txt --single-version-externally-managed --compile --user --prefix= --home=/tmp/pip-target-8zleredw Check the logs for full command output.`

**Comment by kjmeagher** [comment]
everything works fine for me on cobalt if i do 
```
$ eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/setup.sh`
$ PREFIX=${SROOT} pip install --user git+https://github.com/icecube/nuflux
```

If you need more help, you will need to provide a more detailed description of what you did
