### ISSUE TITLE
Build fails under Ubuntu 20.04

### ISSUE THREAD

**Issue by briedel** [icecube/nuflux#20]
Build fails in container with Ubuntu 20.04 base with:

`docs/meson.build:6:12: ERROR: Command `/usr/bin/git describe --tags --always` failed with status 128.`

https://github.com/icecube/nuflux/blob/c842b479a683d136ac874b24e0ae54031159a17a/docs/meson.build#L6

**Comment by briedel** [comment]
Added context this fails because the containers pull down a tar.gz of the repo and this does not include the `.git` dir. So it might be better to resolve this by setting version separately.

**Comment by kjmeagher** [comment]
fixed in 6c25bb3f58cfd84eabe4d8d12c207e6eda73034c
