### ISSUE TITLE
Could not build wheels for nuflux

### ISSUE THREAD

**Issue by samiur06** [icecube/nuflux#22]
I am trying to install nuflux on cluster. 
My system:
Python 3.8.8
pip 23.2.1 
photospline 2.0.7 

After running `pip3 install --user git+https://github.com/icecube/nuflux` on the terminal, I am getting the following error:
`Could not build wheels for nuflux, which is required to install pyproject.toml-based projects`

I also added `--no-binary :all:` prefix in my command, but came with the same error. What else can I do to install it? (I want to avoid building it from scratch, as I already tried it and faced several other dependency issues that are messy to resolve as cluster user.)

**Comment by samiur06** [comment]
I have attached the error output that contains the details [nuflux.txt](https://github.com/icecube/nuflux/files/12719807/nuflux.txt). There are a few packages that are ignored in the installation process. Note that I am trying to install it on cluster.

**Comment by austinschneider** [comment]
Looks like there is an issue with it finding photospline. Is photospline already installed on the system you're using, or do you have any other information about your environmental setup?

**Comment by samiur06** [comment]
Primarily, I couldn't install photospline  with `conda install -c conda-forge photospline` which had given multiple errors due to gcc version and CXXFLAGS, and CMake. Later the people, who handle the HPC, resolved the issue with installation (I am not exactly sure how they did it). 

Currently, this is the location of photospline that shows up at the prompt:
`>>> import photospline; print(photospline.__file__)`
`/opt/anaconda3/2021.05/lib/python3.8/site-packages/photospline.so`

**Comment by kjmeagher** [comment]
you need to find the location of `libphotospline.so` and set the environment variable `PREFIX` such that `${PREFIX}/lib/libphotospline.so` is found

**Comment by samiur06** [comment]
Did you mean the location of `photospline.so` instead of `libphotospline.so`? Because that's the filename I found running `import photospline; print(photospline.__file__)` in python. It is on the `/opt/anaconda3/2021.05/lib/python3.8/site-pachages` directory, not on any `lib` directory.

**Comment by kjmeagher** [comment]
`python3.8/site-pachages/photospline.so` is the python binding, nuflux doesn't care about that. You need to find the c/c++ shared object that nuflux links against

**Comment by samiur06** [comment]
I found the location of `libphotospline.so`, and now I could install nuflux. Thanks for all the help! :)
